### ISSUE TITLE
CodeTime: Temporarily Disconnect

### ISSUE THREAD

**Issue by itsmeshibintmz** [datreks/codetime-vscode#14]
For two days, CodeTime in VS Code shows " CodeTime: Temporarily Disconnect". It redirects to the code time webpage, but can't log in, showing statistics before the time disconnect occurred. 

![image](https://user-images.githubusercontent.com/52344717/145661208-15bcfb48-68d8-46a1-bbf3-a0c6191b5fa0.png)

![image](https://user-images.githubusercontent.com/52344717/145661214-23df5523-b80d-4437-9732-aa2ff9b3f96d.png)

**Comment by itsmeshibintmz** [comment]
Have tried to refresh the token and add, but didn't work.

**Comment by Navaneethsen** [comment]
Same issue here..

**Comment by si9ma** [comment]
@Navaneethsen @itsmeshibintmz mysql storage space is full and has been repaired

**Comment by itsmeshibintmz** [comment]
Nice to hear, Thanks.
