### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by pvojnisek** [datreks/codetime-vscode#17]
Issue Type: <b>Bug</b>

1. install the extension
2. visit and register at https://codetime.datreks.com
3. copy the token from the site and paste to vscode (> CodeTime: Enter token)
4. CodeTime: Initializing... - freezing in the status bar info

If I remove the extension and reinstall it the same happens.

Error in the log (Extensions page in vscode / Runtime Status tab):
```
Cannot read property 'statusCode' of undefined
```

Extension version: 0.0.15
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.15.15-76051515-generic
Restricted Mode: No
Remote OS version: Linux x64 5.15.15-76051515-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 1397)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|30.79GB (2.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id b71d64af-bcc3-42a4-9e58-5f43691ffd66|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 5.15.15-76051515-generic|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 1400)|
|Memory (System)|30.79GB (2.16GB free)|
|VM|0%|
</details>

**Comment by Jannchie** [comment]
Thank you for your support and for bringing this issue to our attention. We are pleased to inform you that we have rewritten the code and the dashboard is now accessible at https://codetime.dev. We understand that we may not have met your expectations in the past, but moving forward, we will make every effort to ensure the stability of our service.
