### ISSUE TITLE
Could  provide a way to view the codetime that we can select time range?

### ISSUE THREAD

**Issue by Isshiki-Aimo** [datreks/codetime-vscode#18]
now we just can see  the total time.sometimes i just want to see How long have I been coding this month or this week to check if I've practiced enough

**Comment by Jannchie** [comment]
Please accept my apologies for the delayed response. I wanted to let you know that we have redesigned the front-end page to enhance your experience. 

You can now access the information you need on the https://codetime.dev/dashboard page and select the time range that suits you, whether it's a day, week, or month. 

We are continually adding more rich features and queries to ensure that you have the best possible experience. Thank you for your continued interest and support, and please don't hesitate to reach out to us if you have any questions or suggestions.
