### ISSUE TITLE
The time is always 0 seconds

### ISSUE THREAD

**Issue by Oyyko** [datreks/codetime-vscode#21]
I installed the extension on vscode. And coding for some hours.
But the time is 0 seconds.
Wakatime can work properly.
I guess the reason is that I am using a proxy.
My System is Linux. I use Clash on Windows(just a software name, it runs on linux) as my proxy software.
Maybe the CodeTime Extension cannot work on a system which uses a proxy?

**Comment by ddmbb** [comment]
I just started having this happen earlier this week.  Everything was working fine until the most recent vscode update and now it stays at 0m despite uninstalling/reinstalling.

**Comment by si9ma** [comment]
@ddmbb There may be some bugs here, we are optimizing and refactoring!
