### ISSUE TITLE
时间一直不更新

### ISSUE THREAD

**Issue by SZnAl** [datreks/codetime-vscode#22]
长时间的使用vscode，但是下面插件显示的时间与网页并没有进行更新，这个状况经常出现，非偶现。

**Comment by si9ma** [comment]
@SZnAl 现在数据计算比较慢，已经在优化重构了！

**Comment by SZnAl** [comment]
> @SZnAl 现在数据计算比较慢，已经在优化重构了！

好的，这种情况持续挺久了，也感谢大佬的付出
