### ISSUE TITLE
Can't authenticate with GitHub

### ISSUE THREAD

**Issue by ThomasRobertson** [datreks/codetime-vscode#23]
Hi !

I can't use GitHub to login on the website. After clicking on GitHub Login, I get redirects to a web page saying :

```{"code":-1,"message":"Error 1290: The MySQL server is running with the LOCK_WRITE_GROWTH option so it cannot execute this statement"}```

The URL look like that : ```https://codetime-api.datreks.com/auth/github/callback?code=3f4feXXXXXXXXXXXXXXX&state=%2F```

**Comment by si9ma** [comment]
@ThomasRobertson server expired, it has been fixed!

**Comment by RockBacon9922** [comment]
I have only just found this project and having this issue @si9ma.

**Comment by leonardorrodrigues** [comment]
I have the same problem.

**Comment by Elfo1507** [comment]
Just found this extension in vscode and tried to login with github, but had the same problem

**Comment by Jannchie** [comment]
I apologize for the delay and any inconvenience caused. I take full responsibility for the recent issue and have taken immediate action to rewrite the backend to prevent it from happening again. 

Your satisfaction is my top priority, and I am committed to doing everything I can to make things right for you. Thank you for your understanding and patience, and please let me know if you have any further concerns.
