### ISSUE TITLE
Could there be a way to connect to custom servers?

### ISSUE THREAD

**Issue by RockBacon9922** [datreks/codetime-vscode#24]
Could there be a way that we could use our own dedicated server? Currently you can only input an api key which connects to the public server. Option in settings to modify the api url? Would be useful as the current public server doesn't seem to be working.

**Comment by Jannchie** [comment]
I want to apologize for the delay in my response and any inconvenience it may have caused. I am pleased to inform you that your request has been fulfilled, and the current vscode settings page now allows you to select your own api address. 

Additionally, I have re-implemented the backend and made it more stable, which should significantly improve your experience. 

I regret any disturbance that this may have caused and assure you that we are committed to providing you with the best possible service. Thank you for your patience and understanding, and please let us know if there is anything else we can do to further improve your experience.
