### ISSUE TITLE
在没有数据（初次使用）的情况下访问网页仪表板，会出现“startDate or endDate is not exists”报错

### ISSUE THREAD

**Issue by JerrySimple** [datreks/codetime-vscode#27]
![image](https://user-images.githubusercontent.com/75707484/220225173-e1f16360-6f7e-4011-8ab9-24e0b2c4a57e.png)

**Comment by Jannchie** [comment]
感谢您的反馈，我们会尽快排查并解决问题。

**Comment by Jannchie** [comment]
我们已经成功定位了问题。这是我们绘制日历图的一个 bug，在没有数据是会抛出一个错误。我们已经修复了它。再次感谢您的反馈。
