### ISSUE TITLE
统计时间不准确

### ISSUE THREAD

**Issue by SZnAl** [datreks/codetime-vscode#28]
在这次升级之前，就已经出现过总计时间不准确的问题。
这次升级之后彻底不准确
总计时间之前已达上百小时，现在不到一百小时

**Comment by Jannchie** [comment]
你好，感谢您的反馈。

这也许是正常现象。之前存在重复统计的问题。同一时间段可能被多次统计，尤其是在同时打开多个窗口编写时。新算法解决了这个问题，所以统计时长会减少。

之前由于服务器不稳定，还存在部分时间段没有统计上的问题。所以即使存在多次统计，总时长仍然会低于你的体感。很抱歉对您造成了困扰。

我们期望新的算法下服务器能保持稳定，从而不会再次遗漏数据。希望今后能够提供更加优质的使用体验。
