### ISSUE TITLE
the dashboard is not updated

### ISSUE THREAD

**Issue by lindXdeep** [datreks/codetime-vscode#3]
I entered token, and trying typed code, but the data is not updated

![image](https://user-images.githubusercontent.com/11368634/109412620-a5a29500-79b1-11eb-9d06-932bf1876281.png)

What could be wrong?

**Comment by Jannchie** [comment]
The calculation of the data may take some time. I'm checking to see if the data is properly recorded.

**Comment by Jannchie** [comment]
Now CodeTime should be able to display your data properly, please check.

Thanks for using CodeTime.

**Comment by lindXdeep** [comment]
it working! thank you too
