### ISSUE TITLE
Can't log in!

### ISSUE THREAD

**Issue by aidanlowrie** [datreks/codetime-vscode#30]
Hi, trying to use codetime but when I try to sign up with GitHub I get this error:

{"code":-1,"message":"Error 1290: The MySQL server is running with the LOCK_WRITE_GROWTH option so it cannot execute this statement"}

**Comment by Jannchie** [comment]
We appreciate your support and would like to inform you that our service has now been fully restored to normal. We acknowledge that we may not have performed up to our best in the past, but moving forward, we will make every effort to ensure the stability of our service.
