### ISSUE TITLE
Codetime not starting

### ISSUE THREAD

**Issue by CaptainStabs** [datreks/codetime-vscode#31]
It does not change even after hours of being open.
![image](https://user-images.githubusercontent.com/40151222/224575009-97f7f256-387a-41f7-910e-fd75e76d49a8.png)
![image](https://user-images.githubusercontent.com/40151222/224575060-224a8e0e-bc6d-485e-a968-7a6faf124b99.png)

I've reinstalled it over a hundred times now and nothing has fixed it...

**Comment by Jannchie** [comment]
Thank you for reaching out to us and reporting this issue. Based on the information you have provided, it appears that you may have mistakenly accessed the wrong repository and found another plugin with the same name.
