### ISSUE TITLE
Why the app asks for write permission including the organization I work for?

### ISSUE THREAD

**Issue by lourenzo** [datreks/codetime-vscode#33]
It would be much better if there was only read access asked, and if I could opt-out on sharing info about the organization I work for.
The app is nice, but why the write permission? What if all those users that give write perm end up in the wrong hands?

**Comment by Jannchie** [comment]
Thank you for your feedback. This may be a misunderstanding.

In reality, we only accessed a portion of the personal profile of some GitHub accounts. We did not need nor attempt to access any GitHub information including repositories, organizations, etc.

May I see a screenshot of the authorization request screen?

**Comment by Jannchie** [comment]
https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/differences-between-github-apps-and-oauth-apps#token-based-identification

I confirmed to the authorization page.
It looks like github's oauth doesn't seem to control the granularity of access.

**Comment by Jannchie** [comment]
Ah, we have now noticed that there is a problem with the scope setting. Please take a moment and we'll make the change right away. It will require minimal read access. 

Thank you for pointing out the problem.

**Comment by Jannchie** [comment]
We have fixed this issue. Please confirm!
