### ISSUE TITLE
In Android studio this plug-in is not working

### ISSUE THREAD

**Issue by MySelfMukundPradhan** [datreks/codetime-vscode#35]
Hi,
In Android studio this plugin is available but when we enter the token it shows Invalid token? Can you please update the same.
<img width="713" alt="Screenshot 2023-05-21 at 11 09 46 PM" src="https://github.com/datreks/codetime-vscode/assets/134202019/fa3e1c7f-de08-41b3-b589-a7db2ba5662c">

**Comment by si9ma** [comment]
> I also got the same "invalid token" window on PhpStorm. Probably a problem with the plugin for all JetBrains IDEs.

@dkage I'm working on it.

**Comment by intbjw** [comment]
me too

**Comment by si9ma** [comment]
@dkage @intbjw have been fixed, you can try it out and see if there are any problems

**Comment by dkage** [comment]
Working great now, thanks mate. I guess you can close the issue @si9ma.
