### ISSUE TITLE
opinion

### ISSUE THREAD

**Issue by Cicada-S** [datreks/codetime-vscode#36]
I hope the author can add multiple languages to the dashboard

**Comment by Jannchie** [comment]
Thank you for your feedback and use,! We will add support for i18n as soon as possible.

**Comment by Jannchie** [comment]
We now have support for switching between Chinese and English (on the settings page).

**Comment by Cicada-S** [comment]
Okay, thank you very much. This is a very good project

**Comment by yongen9696** [comment]
Hi! Thanks for making this extension for everyone @Jannchie. Is it possible to put the CodeTime dashboard into our own user's GitHub profile?
