### ISSUE TITLE
Status bar event listeners 

### ISSUE THREAD

**Issue by DevVali** [datreks/codetime-vscode#37]
Hi 👋. I would like to ask a question about the code - on what event listener(s) does the status bar get updated? 

Thank you.

**Comment by Jannchie** [comment]
https://github.com/datreks/codetime-vscode/blob/44e85e9c444c10c5dcdbf6e756a8bb4df0938289/src/codetime.ts#L93C1-L97C18

We poll instead of listening for events.
Also, the content of the status bar will be modified when initialization and reporting information fails.
