### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MasterBrian99** [datreks/codetime-vscode#4]
this is an amazing project.i used so many time trackers.but this is the best one i used.it got everything i need.
my issue is about vs code time show.
![https://i.imgur.com/UUxOoZD.png](https://i.imgur.com/UUxOoZD.png) .
can we get a daily average instead of total  average.
![https://i.imgur.com/lgEZ3fi.png](https://i.imgur.com/lgEZ3fi.png)

personally, i don't want to see my total.i need my daily average.
again,thank you for this great project.

**Comment by Jannchie** [comment]
This is a good proposal.
I will make it an option in the next version that you can choose to display the total time or the time of day.

**Comment by Jannchie** [comment]
@MasterBrian99 I have released a new version in which you can choose to display the daily average coding time, total coding time, or today coding time in the status bar.

**Comment by MasterBrian99** [comment]
thank you !
