### ISSUE TITLE
What metric do you use to log the time ?

### ISSUE THREAD

**Issue by billmdevs** [datreks/codetime-vscode#40]
What metric do you use to log the time ? 
Is it total time spent in editor(idle time included) or 
time "spent doing something" in editor(like moving the mouse and/or keyboard) ?

**Comment by Jannchie** [comment]
Simply put, when a VSCode event is triggered, we will report a message. This mainly includes actions such as input, scroll, and file switching.

https://github.com/datreks/codetime-vscode/blob/master/src/events.ts

**Comment by billmdevs** [comment]
Thank you very much!
