### ISSUE TITLE
Error Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by Giovani-Gomes** [datreks/codetime-vscode#42]
For some time the Codetime is starting. Please provide the problem response **code 401 (Not authorized)**. Both VS (Visual Studio) and Intlijj. Well this starting. I gave up and installed it again and nothing worked. What could've happened? 

I am sorry my English.

![Captura de tela de 2024-10-15 19-53-52](https://github.com/user-attachments/assets/ffe83e69-a242-4e80-b213-7ed3e69a19d1)

**Comment by Jannchie** [comment]
Our website is www.codetime.dev. It seems that you are not using our service, even though the name is also codetime.

**Comment by Giovani-Gomes** [comment]
"In VS CODE, I managed to do it, but in JetBrains IntelliJ, I'm encountering the following problem:"
![Captura de tela de 2024-10-18 03-19-44](https://github.com/user-attachments/assets/0b3fa370-0cc7-4edf-93e9-0b604e4fd3fd)

"I did my best, but it always says 'invalid token'."

**Comment by Jannchie** [comment]
I’m sorry, our IDEA plugin might be having issues. It hasn’t been updated in a long time, and the person responsible for this part is no longer available. We will address this as soon as possible!

**Comment by Giovani-Gomes** [comment]
> I’m sorry, our IDEA plugin might be having issues. It hasn’t been updated in a long time, and the person responsible for this part is no longer available. We will address this as soon as possible!

In Vscode it is normal, but in Intellij there is a problem. I did everything here, and it didn't work. I realized when I saw that it hadn't been working for a few days.

**Comment by Jannchie** [comment]
Hello, I have rewritten the plugin for IDEA, but it still needs to be reviewed. It should be ready for use in a day or two!

**Comment by Jannchie** [comment]
It seems that our new JetBrains plugin is now live! 

You can access it here: https://plugins.jetbrains.com/plugin/25617-codetime/. Please note that it is an entirely new plugin, so do not upgrade from the old plugin. Instead, uninstall the original plugin and reinstall this one.

**Comment by Giovani-Gomes** [comment]
Excellent! I tested it and it's working. Thanks. Sorry for the inconvenience.
