### ISSUE TITLE
CodeTime: Token validation failed

### ISSUE THREAD

**Issue by ronilaukkarinen** [datreks/codetime-vscode#5]
When I go to [codetime.datreks.com](http://codetime.datreks.com/) to auth, I get:

```
{"code":-1,"message":"Error 1290: The MySQL server is running with the LOCK_WRITE_GROWTH option so it cannot execute this statement"}
```

Using Visual Studio Code 1.56-insiders.

**Comment by si9ma** [comment]
@ronilaukkarinen Thanks for the feedback, I will fix it soon.

**Comment by si9ma** [comment]
@ronilaukkarinen The problem has been fixed, thanks for your feedback.
