### ISSUE TITLE
Stuck on 6 minutes

### ISSUE THREAD

**Issue by awesomelewis2007** [datreks/codetime-vscode#6]
I don't know why but code time is stuck on 6 minutes
![image](https://user-images.githubusercontent.com/60709927/123142708-a1fbb800-d451-11eb-8f94-1b36a0a62463.png)

**Comment by si9ma** [comment]
@awesomelewis2007 Are there still problem?

**Comment by awesomelewis2007** [comment]
Yes I reinstalled the extension but the time counter did not change

**Comment by si9ma** [comment]
@awesomelewis2007 There may be some delay in the data. Are there still problem?

**Comment by awesomelewis2007** [comment]
yes its been 1 week

**Comment by awesomelewis2007** [comment]
![image](https://user-images.githubusercontent.com/60709927/123480695-a1eaec00-d5fa-11eb-89b6-e513fa67d3e8.png)
@si9ma seems to work now thanks for your help

PS: I love this extension by the way
