### ISSUE TITLE
the today code time statistics showing at the bottom of vsc has stopped

### ISSUE THREAD

**Issue by wiz-lee** [datreks/codetime-vscode#9]
My computer shut down abnormally yesterday, when i rebooted this morning and opened vsc, the statistics at the bottom was just stopped at 7hrs. I think it may be the automatic recovery mechanism of vsc that caused this extension cannot work.

**Comment by si9ma** [comment]
@wiz-lee Time-consuming calculations are done by the backend, and the amount of data is relatively large, so there will be a certain delay
